import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Description from "@/components/description";
// import Item from "@/components/Item";
// import Itemlist from "@/components/Itemlist";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "NafisSirChhaurahi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Itemlist></Itemlist> */}

     
        <Navbar/>

           {children}
      <Description></Description>


      </body>
    </html>
  );
}
