import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";  // Direct import now
import Description from "@/components/description";
import Watermark from "@/components/Watermark";
// import { Skeleton } from "@/components/ui/skeleton";
import { Suspense } from "react";
import Loading from "./loading";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "NafisSirChhaurahi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />  {/* Direct import */}
        <Watermark></Watermark>
        {/* <Skeleton></Skeleton> */}
        <Suspense fallback={<Loading/>}>
        {children}
        </Suspense>
        <Description />
      </body>
    </html>
  );
}






///

// import './globals.css';
// import Watermark from './components/Watermark';
// import { useEffect } from "react";

// export default function RootLayout({ children }) {
//   useEffect(() => {
//     const disableRightClick = (e) => e.preventDefault();
//     document.addEventListener('contextmenu', disableRightClick);

//     return () => {
//       document.removeEventListener('contextmenu', disableRightClick);
//     };
//   }, []);

//   return (
//     <html lang="en">
//       <body>
//         <Watermark />
//         {children}
//       </body>
//     </html>
//   );
// }
